import type { ClassDef } from "@/common/domain/classes/types";
import { goldenColor } from "@/common/domain/classes/packs/utils";

// LVIS v1 — 1203 long-tail object categories
const LVIS_NAMES = [
  "aerosol can", "air conditioner", "airplane", "alarm clock", "alcohol",
  "alligator", "almond", "ambulance", "amplifier", "anklet", "antenna", "apple",
  "applesauce", "apricot", "apron", "aquarium", "arctic shoe", "armband",
  "armchair", "armoire", "armor", "artichoke", "trash can", "ashtray",
  "asparagus", "atomizer", "avocado", "award", "awning", "ax", "baboon",
  "baby buggy", "basketball backboard", "backpack", "handbag", "suitcase",
  "bagel", "bagpipe", "baguette", "bait", "ball", "ballet skirt", "balloon",
  "bamboo", "banana", "Band Aid", "bandage", "bandanna", "banjo", "banner",
  "barbell", "barge", "barrel", "barrette", "barrow", "baseball base",
  "baseball", "baseball bat", "baseball cap", "baseball glove", "basket",
  "basketball", "tuba", "bat", "bath mat", "bath towel", "bathrobe", "bathtub",
  "batter", "battery", "beachball", "bead", "bean curd", "beanbag", "beanie",
  "bear", "bed", "bedpan", "bedspread", "cow", "beef", "beeper", "beer bottle",
  "beer can", "beetle", "bell", "bell pepper", "belt", "belt buckle", "bench",
  "beret", "bib", "Bible", "bicycle", "visor", "billboard", "binder",
  "binoculars", "bird", "birdfeeder", "birdbath", "birdcage", "birdhouse",
  "birthday cake", "birthday card", "pirate flag", "black sheep", "blackberry",
  "blackboard", "blanket", "blazer", "blender", "blimp", "blinker", "blouse",
  "blueberry", "gameboard", "boat", "bob", "bobbin", "bobby pin", "boiled egg",
  "bolo tie", "deadbolt", "bolt", "bonnet", "book", "bookcase", "booklet",
  "bookmark", "boom microphone", "boot", "bottle", "bottle opener", "bouquet",
  "bow", "bow", "bow-tie", "bowl", "pipe bowl", "bowler hat", "bowling ball",
  "box", "boxing glove", "suspenders", "bracelet", "brass plaque", "brassiere",
  "bread-bin", "bread", "breechcloth", "bridal gown", "briefcase", "broccoli",
  "broach", "broom", "brownie", "brussels sprouts", "bubble gum", "bucket",
  "horse buggy", "horned cow", "bulldog", "bulldozer", "bullet train",
  "bulletin board", "bulletproof vest", "bullhorn", "bun", "bunk bed", "buoy",
  "burrito", "bus", "business card", "butter", "butterfly", "button", "cab",
  "cabana", "cabin car", "cabinet", "locker", "cake", "calculator", "calendar",
  "calf", "camcorder", "camel", "camera", "camera lens", "camper", "can",
  "can opener", "candle", "candle holder", "candy bar", "candy cane",
  "walking cane", "canister", "canoe", "cantaloupe", "canteen", "cap",
  "bottle cap", "cape", "cappuccino", "car", "railcar", "elevator car",
  "car battery", "identity card", "card", "cardigan", "cargo ship", "carnation",
  "horse carriage", "carrot", "tote bag", "cart", "carton", "cash register",
  "casserole", "cassette", "cast", "cat", "cauliflower", "cayenne", "CD player",
  "celery", "cell phone", "chain mail", "chair", "chaise longue", "chalice",
  "chandelier", "chap", "checkbook", "checkerboard", "cherry", "chessboard",
  "chicken", "chickpea", "chili", "chime", "chinaware", "potato chip",
  "poker chip", "chocolate bar", "chocolate cake", "chocolate milk",
  "chocolate mousse", "choker", "chopping board", "chopstick", "Christmas tree",
  "slide", "cider", "cigar box", "cigarette", "cigarette case", "cistern",
  "clarinet", "clasp", "cleanser", "cleat", "clementine", "clip", "clipboard",
  "clippers", "cloak", "clock", "clock tower", "clothes hamper", "clothespin",
  "clutch bag", "coaster", "coat", "coat hanger", "coatrack", "rooster",
  "cockroach", "cocoa", "coconut", "coffee maker", "coffee table", "coffeepot",
  "coil", "coin", "colander", "coleslaw", "coloring material",
  "combination lock", "pacifier", "comic book", "compass", "computer keyboard",
  "condiment", "traffic cone", "controller", "convertible", "sofa bed",
  "cooker", "cookie", "cooking utensil", "cooler", "cork", "corkboard",
  "corkscrew", "corn", "cornbread", "cornet", "cornice", "cornmeal", "corset",
  "costume", "cougar", "coverall", "cowbell", "cowboy hat", "crab", "crabmeat",
  "cracker", "crepe", "crate", "crayon", "cream pitcher", "croissant", "crib",
  "crock pot", "crossbar", "crouton", "crow", "crowbar", "crown", "crucifix",
  "cruise ship", "police cruiser", "crumb", "crutch", "cub", "cube",
  "cucumber", "cufflink", "cup", "trophy cup", "cupboard", "cupcake",
  "hair curler", "curling iron", "curtain", "cushion", "cylinder", "cymbal",
  "dagger", "dalmatian", "dartboard", "date", "deck chair", "deer",
  "dental floss", "desk", "detergent", "diaper", "diary", "die", "dinghy",
  "dining table", "tuxedo", "dish", "dish antenna", "dishrag", "dishtowel",
  "dishwasher", "dishwasher detergent", "dispenser", "diving board", "paper cup",
  "dog", "dog collar", "doll", "dollar", "dollhouse", "dolphin", "donkey",
  "doorknob", "doormat", "donut", "dove", "dragonfly", "drawer", "underwear",
  "dress", "dress hat", "dress suit", "dresser", "drill", "drone", "dropper",
  "drum", "drumstick", "duck", "duckling", "duct tape", "duffel bag",
  "dumbbell", "dumpster", "dustpan", "eagle", "earphone", "earplug", "earring",
  "easel", "eclair", "eel", "egg", "egg roll", "egg yolk", "eggbeater",
  "eggplant", "electric chair", "refrigerator", "elephant", "elk", "envelope",
  "eraser", "escargot", "eyepatch", "falcon", "fan", "faucet", "fedora",
  "ferret", "Ferris wheel", "ferry", "fig", "fighter jet", "figurine",
  "file cabinet", "file", "fire alarm", "fire engine", "fire extinguisher",
  "fire hose", "fireplace", "fire hydrant", "first-aid kit", "fish", "fish food",
  "fishbowl", "fishing rod", "flag", "flagpole", "flamingo", "flannel", "flap",
  "flash", "flashlight", "fleece", "flip-flop", "flipper", "flower arrangement",
  "flute glass", "foal", "folding chair", "food processor",
  "American football", "football helmet", "footstool", "fork", "forklift",
  "freight car", "French toast", "air freshener", "frisbee", "frog",
  "fruit juice", "frying pan", "fudge", "funnel", "futon", "muzzle", "garbage",
  "garbage truck", "garden hose", "mouthwash", "gargoyle", "garlic", "gasmask",
  "gazelle", "gelatin", "gemstone", "generator", "giant panda", "gift wrap",
  "ginger", "giraffe", "sash", "drinking glass", "globe", "glove", "goat",
  "goggles", "goldfish", "golf club", "golf cart", "gondola", "goose",
  "gorilla", "gourd", "grape", "grater", "gravestone", "gravy boat",
  "green bean", "green onion", "griddle", "grille", "grits", "grizzly bear",
  "grocery bag", "guitar", "seagull", "gun", "hairbrush", "hairnet", "hairpin",
  "halter top", "ham", "hamburger", "hammer", "hammock", "hamper", "hamster",
  "hair dryer", "hand mirror", "hand towel", "handcart", "handcuff",
  "handkerchief", "handle", "handsaw", "hardback book", "harmonium", "hat",
  "hatbox", "veil", "headband", "headboard", "headlight", "headscarf",
  "headset", "headstall", "heart", "heater", "helicopter", "helmet", "heron",
  "highchair", "hinge", "hippopotamus", "hockey stick", "pig", "home plate",
  "honey", "exhaust hood", "hook", "hookah", "hornet", "horse", "hosepipe",
  "hot-air balloon", "hotplate", "hot sauce", "hourglass", "houseboat",
  "hummingbird", "hummus", "polar bear", "ice cream", "popsicle", "ice maker",
  "ice pack", "ice skate", "lighter", "inhaler", "iPod", "iron", "ironing board",
  "jacket", "jam", "jar", "jeans", "jeep", "jelly bean", "jersey",
  "jet plane", "jewel", "jewelry", "joystick", "jumpsuit", "kayak", "keg",
  "kennel", "kettle", "key", "keycard", "kilt", "kimono", "kitchen sink",
  "kitchen table", "kite", "kitten", "kiwi fruit", "knee pad", "knife",
  "knitting needle", "knob", "doorknocker", "koala", "lab coat", "ladder",
  "ladle", "ladybug", "lamb", "lamb chop", "lamp", "lamppost", "lampshade",
  "lantern", "lanyard", "laptop", "lasagna", "latch", "lawn mower", "leather",
  "legging", "Lego", "legume", "lemon", "lemonade", "lettuce", "license plate",
  "life buoy", "life jacket", "lightbulb", "lightning rod", "lime", "limousine",
  "lion", "lip balm", "liquor", "lizard", "log", "lollipop", "stereo speaker",
  "loveseat", "machine gun", "magazine", "magnet", "mail slot", "mailbox",
  "mallard", "mallet", "mammoth", "manatee", "mandarin orange", "manger",
  "manhole", "map", "marker", "martini", "mascot", "mashed potato", "masher",
  "mask", "mast", "gym mat", "matchbox", "mattress", "measuring cup",
  "ruler", "meatball", "medicine", "melon", "microphone", "microscope",
  "microwave oven", "milestone", "milk", "milk can", "milkshake", "minivan",
  "mint candy", "mirror", "mitten", "mixer", "money", "computer monitor",
  "monkey", "motor", "motor scooter", "motor vehicle", "motorcycle",
  "pitcher's mound", "computer mouse", "mousepad", "muffin", "mug", "mushroom",
  "piano stool", "musical instrument", "nailfile", "napkin", "neckerchief",
  "necklace", "necktie", "needle", "nest", "newspaper", "newsstand",
  "nightshirt", "nosebag", "noseband", "notebook", "notepad", "nut",
  "nutcracker", "oar", "octopus food", "octopus", "oil lamp", "olive oil",
  "omelet", "onion", "orange", "orange juice", "ostrich", "ottoman", "oven",
  "overalls", "owl", "packet", "inkpad", "pad", "paddle", "padlock",
  "paintbrush", "painting", "pajamas", "palette", "cooking pan", "metal pan",
  "pancake", "pantyhose", "papaya", "paper plate", "paper towel",
  "paperback book", "paperweight", "parachute", "parakeet", "parasail",
  "parasol", "parchment", "parka", "parking meter", "parrot", "passenger car",
  "passenger ship", "passport", "pastry", "patty", "pea", "peach",
  "peanut butter", "pear", "peeler", "pegleg", "pegboard", "pelican", "pen",
  "pencil", "pencil box", "pencil sharpener", "pendulum", "penguin", "pennant",
  "penny", "peppercorn", "pepper mill", "perfume", "persimmon", "person",
  "pet", "church pew", "phonebook", "phonograph record", "piano", "pickle",
  "pickup truck", "pie", "pigeon", "piggy bank", "pillow", "pin", "pineapple",
  "pinecone", "ping-pong ball", "pinwheel", "tobacco pipe", "pipe", "pistol",
  "pita bread", "pitcher", "pitchfork", "pizza", "place mat", "plate",
  "platter", "playpen", "pliers", "plow", "plume", "pocket watch", "pocketknife",
  "poker", "pole", "polo shirt", "poncho", "pony", "pool table", "soda",
  "public postbox", "postcard", "poster", "pot", "flowerpot", "potato",
  "potholder", "pottery", "pouch", "excavator", "shrimp", "pretzel", "printer",
  "missile", "projector", "propeller", "prune", "pudding", "puffer fish",
  "puffin", "pug", "pumpkin", "puncher", "puppet", "puppy", "quesadilla",
  "quiche", "quilt", "rabbit", "race car", "racket", "radar", "radiator",
  "radio", "radish", "raft", "rag doll", "raincoat", "ram", "raspberry", "rat",
  "razorblade", "reamer", "rearview mirror", "receipt", "recliner",
  "record player", "reflector", "remote control", "rhinoceros", "rib",
  "rifle", "ring", "river boat", "road map", "robe", "rocking chair", "rodent",
  "roller skate", "Rollerblade", "rolling pin", "root beer", "router",
  "rubber band", "carpet runner", "plastic bag", "saddle", "saddle blanket",
  "saddlebag", "safety pin", "sail", "salad", "salad bowl", "salami",
  "salmon fish", "salmon food", "salsa", "saltshaker", "sandal", "sandwich",
  "satchel", "saucepan", "saucer", "sausage", "sawhorse", "saxophone",
  "scale", "scarecrow", "scarf", "school bus", "scissors", "scoreboard",
  "scraper", "screwdriver", "scrubbing brush", "sculpture", "seabird",
  "seahorse", "seaplane", "seashell", "sewing machine", "shaker", "shampoo",
  "shark", "sharpener", "Sharpie", "electric shaver", "shaving cream", "shawl",
  "shears", "sheep", "sheepdog", "sherbet", "shield", "shirt", "sneaker",
  "shopping bag", "shopping cart", "shorts", "shot glass", "shoulder bag",
  "shovel", "shower head", "shower cap", "shower curtain", "paper shredder",
  "signboard", "silo", "sink", "skateboard", "skewer", "ski", "ski boot",
  "ski jacket", "ski pole", "skirt", "skullcap", "sled", "sleeping bag",
  "sling", "slipper", "smoothie", "snake", "snowboard", "snowman",
  "snowmobile", "soap", "soccer ball", "sock", "sofa", "softball",
  "solar panel", "sombrero", "soup", "soup bowl", "soupspoon", "sour cream",
  "soya milk", "space shuttle", "sparkler", "spatula", "spear", "eyeglasses",
  "spice rack", "spider", "crayfish", "sponge", "spoon", "sportswear",
  "spotlight", "squid", "squirrel", "stagecoach", "stapler", "starfish",
  "statue", "steak", "steak knife", "steering wheel", "stepladder",
  "step stool", "stereo", "stew", "stirrer", "stirrup", "stool", "stop sign",
  "brake light", "stove", "strainer", "strap", "drinking straw", "strawberry",
  "street sign", "streetlight", "string cheese", "stylus", "subwoofer",
  "sugar bowl", "sugarcane", "suit", "sunflower", "sunglasses", "sunhat",
  "surfboard", "sushi", "mop", "sweat pants", "sweatband", "sweater",
  "sweatshirt", "sweet potato", "swimsuit", "sword", "syringe", "Tabasco sauce",
  "ping-pong table", "table", "table lamp", "tablecloth", "tachometer", "taco",
  "tag", "taillight", "tambourine", "army tank", "storage tank", "tank top",
  "tape", "tape measure", "tapestry", "tarp", "tartan", "tassel", "tea bag",
  "teacup", "teakettle", "teapot", "teddy bear", "telephone",
  "telephone booth", "telephone pole", "telephoto lens", "tv camera",
  "television", "tennis ball", "tennis racket", "tequila", "thermometer",
  "thermos", "thermostat", "thimble", "thread", "thumbtack", "tiara", "tiger",
  "tights", "timer", "tinfoil", "tinsel", "tissue paper", "toast", "toaster",
  "toaster oven", "toilet", "toilet paper", "tomato", "tongs", "toolbox",
  "toothbrush", "toothpaste", "toothpick", "cover", "tortilla", "tow truck",
  "towel", "towel rack", "toy", "tractor", "traffic light", "dirt bike",
  "semi truck", "train", "trampoline", "tray", "trench coat", "triangle",
  "tricycle", "tripod", "trousers", "truck", "chocolate truffle", "trunk",
  "vat", "turban", "turkey food", "turnip", "turtle", "turtleneck",
  "typewriter", "umbrella", "underwear", "unicycle", "urinal", "urn",
  "vacuum cleaner", "vase", "vending machine", "air vent", "vest", "videotape",
  "vinegar", "violin", "vodka", "volleyball", "vulture", "waffle",
  "waffle iron", "wagon", "wagon wheel", "walking stick", "wall clock",
  "wall socket", "wallet", "walrus", "wardrobe", "washbasin",
  "washing machine", "watch", "water bottle", "water cooler", "water faucet",
  "water heater", "water jug", "water gun", "jet ski", "water ski",
  "water tower", "watering can", "watermelon", "weathervane", "webcam",
  "wedding cake", "wedding ring", "wet suit", "wheel", "wheelchair",
  "whipped cream", "whistle", "wig", "wind chime", "windmill", "window box",
  "windshield wiper", "windsock", "wine bottle", "wine bucket", "wineglass",
  "blinder", "wok", "wolf", "wooden spoon", "wreath", "wrench", "wristband",
  "wristlet", "yacht", "yogurt", "yoke", "zebra", "zucchini",
];

export const lvisClasses: ClassDef[] = LVIS_NAMES.map((name, i) => ({
  id: i,
  name,
  color: goldenColor(i),
  source: "preset",
}));
